export const PAGE_IDS = {
  ANALYTICS: 'analytics',
  USERS: 'users',
  LINES: 'lines',
  MATERIALS: 'materials',
  CHEMISTRY: 'chemistry',
  RECIPES: 'recipes',
  OTK: 'otk',
  WAREHOUSE: 'warehouse',
  CLIENTS: 'clients',
  SALES: 'sales',
  ORDERS: 'orders',
  PAYMENTS: 'payments',
  RETURNS: 'returns',
  DEFECTS: 'defects',
  REWORK_REQUESTS: 'rework-requests',
};

export const PAGE_ROUTES = {
  [PAGE_IDS.ANALYTICS]: '/analytics',
  [PAGE_IDS.USERS]: '/users',
  [PAGE_IDS.LINES]: '/lines',
  [PAGE_IDS.MATERIALS]: '/materials',
  [PAGE_IDS.CHEMISTRY]: '/chemistry',
  [PAGE_IDS.RECIPES]: '/recipes',
  [PAGE_IDS.OTK]: '/otk',
  [PAGE_IDS.WAREHOUSE]: '/warehouse',
  [PAGE_IDS.CLIENTS]: '/clients',
  [PAGE_IDS.SALES]: '/sales',
  [PAGE_IDS.ORDERS]: '/orders',
  [PAGE_IDS.PAYMENTS]: '/payments',
  [PAGE_IDS.RETURNS]: '/returns',
  [PAGE_IDS.DEFECTS]: '/defects',
  [PAGE_IDS.REWORK_REQUESTS]: '/rework-requests',
};

export const PAGE_LABELS = {
  [PAGE_IDS.ANALYTICS]: 'Аналитика',
  [PAGE_IDS.USERS]: 'Сотрудники',
  [PAGE_IDS.LINES]: 'Линии',
  [PAGE_IDS.MATERIALS]: 'Сырьё',
  [PAGE_IDS.CHEMISTRY]: 'Заготовка',
  [PAGE_IDS.RECIPES]: 'Рецепты',
  [PAGE_IDS.OTK]: 'ОТК',
  [PAGE_IDS.WAREHOUSE]: 'Склад',
  [PAGE_IDS.CLIENTS]: 'Клиенты',
  [PAGE_IDS.SALES]: 'Продажи',
  [PAGE_IDS.ORDERS]: 'Заявки',
  [PAGE_IDS.PAYMENTS]: 'Оплаты',
  [PAGE_IDS.RETURNS]: 'Возвраты',
  [PAGE_IDS.DEFECTS]: 'Брак / переделка',
  [PAGE_IDS.REWORK_REQUESTS]: 'Переделка',
};

/** Группы для вспомогательных подборок (виджеты, ссылки) */
export const PAGE_GROUPS = {
  norms: [PAGE_IDS.RECIPES, PAGE_IDS.MATERIALS],
  production: [PAGE_IDS.CHEMISTRY, PAGE_IDS.OTK],
  finished: [PAGE_IDS.WAREHOUSE],
  main: [PAGE_IDS.ANALYTICS, PAGE_IDS.OTK, PAGE_IDS.WAREHOUSE],
  setup: [PAGE_IDS.MATERIALS, PAGE_IDS.CHEMISTRY, PAGE_IDS.RECIPES],
  admin: [PAGE_IDS.USERS],
  commerce: [PAGE_IDS.CLIENTS, PAGE_IDS.ORDERS, PAGE_IDS.SALES, PAGE_IDS.PAYMENTS, PAGE_IDS.RETURNS, PAGE_IDS.DEFECTS, PAGE_IDS.REWORK_REQUESTS],
};

export const PAGE_ICONS = {
  [PAGE_IDS.ANALYTICS]: 'BarChart2',
  [PAGE_IDS.USERS]: 'Users',
  [PAGE_IDS.LINES]: 'Factory',
  [PAGE_IDS.MATERIALS]: 'Package',
  [PAGE_IDS.CHEMISTRY]: 'Flask',
  [PAGE_IDS.RECIPES]: 'BookOpen',
  [PAGE_IDS.OTK]: 'ShieldCheck',
  [PAGE_IDS.WAREHOUSE]: 'Warehouse',
  [PAGE_IDS.CLIENTS]: 'Building2',
  [PAGE_IDS.SALES]: 'TrendingUp',
  [PAGE_IDS.ORDERS]: 'ClipboardList',
  [PAGE_IDS.PAYMENTS]: 'TrendingUp',
  [PAGE_IDS.RETURNS]: 'Truck',
  [PAGE_IDS.DEFECTS]: 'ShieldCheck',
  [PAGE_IDS.REWORK_REQUESTS]: 'ClipboardCheck',
};
